<#
.SYNOPSIS
    The single manifest-generation transaction: one Book's manifest is generated, stored, and
    committed under that Book's own lock. Dot-sourced; never invoked directly.

.DESCRIPTION
    Plan item 2.2, third rung. The second rung made the ORDER safe -- dirty marker, generation,
    commit pointer last, marker cleared last of all -- so that every crash leaves a state the read
    path can classify. Ordering survives a crash. It does not survive a second writer.

    THIS RUNG MAKES CONCURRENT WRITERS IMPOSSIBLE RATHER THAN MERELY UNLIKELY. The lock is 0.7's
    per-Book lock, the same one every Shelf writer already takes -- not a second lock beside it, as
    PLAN.md 0.7 requires: "Phase 2.2's manifest generations extend this same lock to cover
    dirty-marker creation and commit-pointer publication; they do not introduce a second one." It is
    held from BEFORE the dirty marker is set until AFTER the commit pointer is written, and it wraps
    Save-BookManifest and nothing else.

    A CALLER THAT ALREADY HOLDS THE LOCK PASSES IT IN. Enter-BookLock is not re-entrant -- it wins a
    CreateNew race, so a second acquisition by the same process blocks against itself and then
    throws. Rung 4 retrofits mutators that hold the Book lock across their own mutation, and they
    must extend that same lock over the manifest rather than deadlock against it. -Lock is that
    path: the transaction verifies the handle is for this Book, uses it, and does not release what
    it did not acquire.

    THE MANIFEST IS GENERATED BEFORE THE MARKER IS SET, DELIBERATELY. Generation reads the Book and
    can fail -- an uncatalogued slug is refused outright by rung 1. A failure there must leave no
    dirty marker behind, because a marker with no repair to follow it is a Book that reads
    unavailable forever. Once the marker IS set, a failure leaves it in place on purpose: the Book
    was mutated and its stored manifest is now stale, so refusing until a rebuild is the honest
    state, and it is the bias rung 2 chose -- refusing a good manifest costs a rebuild, serving a
    bad one costs a wrong answer that looks right.

    GENERATION READS BODIES; IT DOES NOT AUTHORIZE READING THEM. Unchanged from rung 1: the caller
    owes the Desk gate, or backfill's explicit closed-content approval, before it gets here.
#>

Set-StrictMode -Version Latest

. (Join-Path $PSScriptRoot 'BookWriteGuard.ps1')
. (Join-Path $PSScriptRoot 'BookManifest.ps1')
. (Join-Path $PSScriptRoot 'BookManifestStore.ps1')

# Rung 7. The lock has always distinguished the two collections and the store now does too, so the
# one way left to get them wrong is to pass a `books/` root with a `shelf` store key -- which would
# lock one Book and write another Book's manifest. Cross-checked here rather than inferred, because
# inferring the collection from the root would make a caller's mistake invisible instead of fatal.
#
# THE ARCHIVES MADE `StartsWith` WRONG. This compared the root against a prefix, and
# `shelf/_archive/godot`.StartsWith('shelf/') is TRUE -- so an archived Book passed as `shelf` and
# would have written its manifest into its ACTIVE twin's store, which is the exact collision rung 7
# built the collection key to prevent. The root is now taken apart by the schema and its OWN manifest
# collection compared for equality, which no prefix can satisfy by accident.
function Assert-BookCollectionMatchesRoot([string]$Collection, [string]$BookRoot) {
    if ($Collection -cnotin (Get-BookManifestCollections)) { throw "Book collection '$Collection' must be one of: $((Get-BookManifestCollections) -join ', ')." }
    $actual = $null
    try { $actual = (Split-BookRoot $BookRoot).manifest_collection }
    catch { throw "Book root '$BookRoot' is not a well-formed Book root, so no collection can answer for it." }
    if ($actual -cne $Collection) {
        throw "Book root '$BookRoot' does not belong to the '$Collection' collection; it belongs to '$actual'. A '$Collection' Book's root starts with '$((Split-BookManifestCollection $Collection).root_prefix)/'."
    }
}

function Invoke-BookManifestTransaction {
    <#
    .SYNOPSIS
        Generate, store, and commit one Book's manifest under that Book's lock.

    .PARAMETER Lock
        A lock handle the caller already holds for this Book. When given, the transaction uses it
        and leaves it held; when omitted, the transaction acquires and releases its own.

    .PARAMETER Manifest
        A manifest already generated by the caller. When omitted, one is generated inside the
        transaction, before the dirty marker is set.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$Workspace,
        [Parameter(Mandatory = $true)][string]$Slug,
        [string]$BookRoot = '',
        [Parameter(Mandatory = $true)][string]$Reason,
        [object]$Manifest = $null,
        [object]$Lock = $null,
        [int]$TimeoutSeconds = 20,
        [string]$Collection = 'shelf'
    )

    if ([string]::IsNullOrWhiteSpace($BookRoot)) { $BookRoot = New-BookRootFromManifestCollection $Collection $Slug }
    Assert-BookCollectionMatchesRoot -Collection $Collection -BookRoot $BookRoot

    # Refused before a lock is taken, so a bad name cannot leave a lock file behind. The store
    # applies the same rule when it builds a path; applying it here too means the refusal happens
    # before any state exists rather than halfway through.
    if ($Slug -cnotmatch '^[a-z0-9][a-z0-9-]*$') {
        throw "Book slug '$Slug' must contain only lowercase letters, digits, and hyphens."
    }

    $ownsLock = $false
    if ($null -ne $Lock) {
        # A handle for the wrong Book is worse than no handle: it would run the whole transaction
        # believing it was protected while another writer held the Book it is actually touching.
        $held = ConvertTo-BookLockName $Lock.book_root
        $wanted = ConvertTo-BookLockName $BookRoot
        if ($held -cne $wanted) {
            throw "The lock handed to this transaction is for '$($Lock.book_root)', not for '$BookRoot'."
        }
    }
    else {
        $Lock = Enter-BookLock -Workspace $Workspace -BookRoot $BookRoot -TimeoutSeconds $TimeoutSeconds
        $ownsLock = $true
    }

    try {
        # Inside the lock, and before the marker: a generation failure must leave nothing behind.
        if ($null -eq $Manifest) {
            # Only the ACTIVE Shelf can be generated from here. A shared Book's pages arrive over MCP
            # and this file has no client and must not grow one; and an ARCHIVED Shelf Book is absent
            # from shelf/_catalog.md by design, so New-BookManifest -- which resolves a slug through
            # that catalog -- would refuse it as uncatalogued. Both cases build the manifest in the
            # caller, which has the pages and the metadata, and hand it in.
            if ($Collection -cne 'shelf') { throw "A '$Collection' Book's manifest must be generated by its caller and passed in; Book '$Slug' arrived without one." }
            $Manifest = New-BookManifest -Workspace $Workspace -Slug $Slug
        }

        $pointer = Save-BookManifest -Workspace $Workspace -Slug $Slug -Manifest $Manifest -Reason $Reason -Collection $Collection

        [pscustomobject]@{
            slug            = $Slug
            book_root       = $BookRoot
            collection      = $Collection
            generation      = $pointer.generation
            manifest_sha256 = $pointer.manifest_sha256
            source_digest   = $pointer.source_digest
            committed_utc   = $pointer.committed_utc
            lock_acquired   = $ownsLock
        }
    }
    catch {
        # Deliberately not cleared. If the marker exists, the mutation that prompted this
        # transaction has already touched the Book, and a refusal is the truthful answer until
        # something rebuilds it.
        throw "The manifest transaction for Book '$Slug' failed and its stored manifest is now marked dirty until rebuilt: $($_.Exception.Message)"
    }
    finally {
        # Only what this transaction acquired. Releasing a caller's lock would end the caller's
        # mutation window in the middle of the caller's mutation.
        if ($ownsLock) { Exit-BookLock -Lock $Lock }
    }
}

# ---------------------------------------------------------------------------------------------------
# The mutation window: what a Shelf writer actually calls.
#
# Rung 4. Invoke-BookManifestTransaction on its own commits a manifest for a Book that was mutated
# some time before -- and "some time before" is the whole problem. Between a writer's last write and
# its call to the transaction there is a window in which the Book has changed and the stored manifest
# still reads `ok`: exactly the silently-stale answer the dirty marker exists to prevent, and PLAN.md
# 2.2 is explicit that the marker goes down BEFORE the mutation, not after it.
#
# So a writer does not call the transaction. It OPENS A MUTATION WINDOW and then closes it:
#
#     $lock     = Enter-BookLock ...
#     $mutation = Enter-BookMutation ... -Lock $lock     # marker down, before the first write
#     ... journal, mutate, verify ...
#     Complete-BookMutation -Mutation $mutation          # generate, store, commit, marker up
#
# and on a failure whose rollback VERIFIED, Undo-BookMutation instead -- the Book is back to the
# state the stored manifest already describes, so the marker must come up or the Book reads
# unavailable forever with nothing left to repair.
#
# COMPLETING NEVER THROWS, AND THAT IS THE POINT. The mutation has already landed and been verified
# by the time it is called. A manifest failure must not roll back the reader's page, note, or rename:
# it leaves the marker down, the Book reads `dirty`, and Discovery refuses to describe it until a
# rebuild. Rung 2's bias, one layer further out -- refusing a good manifest costs a rebuild, serving
# a bad one costs a wrong answer that looks right, and discarding a landed write costs the reader
# their material. It returns a status the writer reports, the way Get-StoredBookManifest does.
# ---------------------------------------------------------------------------------------------------

function Enter-BookMutation {
    <#
    .SYNOPSIS
        Mark a Book dirty before a writer changes it, and hold everything the commit will need.

    .PARAMETER Lock
        Mandatory, and not a convenience: a mutation window without exclusion is a window two
        writers can be inside at once, which is the case rung 3 exists to make impossible. The
        handle must name this Book.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$Workspace,
        [Parameter(Mandatory = $true)][string]$Slug,
        [string]$BookRoot = '',
        [Parameter(Mandatory = $true)][string]$Reason,
        [Parameter(Mandatory = $true)][object]$Lock,
        [string]$Collection = 'shelf'
    )

    if ([string]::IsNullOrWhiteSpace($BookRoot)) { $BookRoot = New-BookRootFromManifestCollection $Collection $Slug }
    Assert-BookCollectionMatchesRoot -Collection $Collection -BookRoot $BookRoot
    if ($Slug -cnotmatch '^[a-z0-9][a-z0-9-]*$') {
        throw "Book slug '$Slug' must contain only lowercase letters, digits, and hyphens."
    }

    $held = ConvertTo-BookLockName $Lock.book_root
    $wanted = ConvertTo-BookLockName $BookRoot
    if ($held -cne $wanted) {
        throw "The lock handed to this mutation is for '$($Lock.book_root)', not for '$BookRoot'."
    }

    $marker = Set-BookManifestDirty -Workspace $Workspace -Slug $Slug -Reason $Reason -Collection $Collection

    [pscustomobject]@{
        workspace  = $Workspace
        slug       = $Slug
        book_root  = $BookRoot
        collection = $Collection
        reason     = $Reason
        lock       = $Lock
        marker     = $marker
    }
}

function Complete-BookMutation {
    <#
    .SYNOPSIS
        Close a mutation window by committing the manifest that describes the change. Never throws.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][object]$Mutation,
        # A manifest the caller generated. Mandatory in practice for a shared Book, whose pages this
        # file cannot read; omitted for the Shelf, which generates inside the transaction.
        [object]$Manifest = $null
    )

    try {
        $pointer = Invoke-BookManifestTransaction `
            -Workspace $Mutation.workspace -Slug $Mutation.slug -BookRoot $Mutation.book_root `
            -Reason $Mutation.reason -Lock $Mutation.lock -Collection $Mutation.collection -Manifest $Manifest
        [pscustomobject]@{
            status     = 'committed'
            slug       = $Mutation.slug
            generation = $pointer.generation
            summary    = "generation $($pointer.generation) committed"
        }
    }
    catch {
        [pscustomobject]@{
            status     = 'dirty'
            slug       = $Mutation.slug
            generation = 0
            summary    = "dirty until rebuilt: $($_.Exception.Message)"
        }
    }
}

function New-BookMutationFailure {
    <#
    .SYNOPSIS
        The result a manifest updater reports when the lock or the mutation window failed. One
        function, so a later edit cannot fix one updater and miss the other.

    .DESCRIPTION
        WHY THIS IS A FUNCTION AND NOT TWO CATCH BLOCKS. Until 2026-09-06 both updaters wrapped
        `Enter-BookLock` AND `Enter-BookMutation` in a single try, then labelled ANY throw from it
        `locked by another writer` -- each asserting in a comment that nothing else could throw.
        Enter-BookMutation, inside that try, validates the slug, validates the collection against
        the Book root, validates the lock's identity, and writes the dirty marker: four ways to
        fail, all reported as contention that had not happened. A shared rebuild hit exactly that
        on 2026-09-05 and the journals could not contradict the label, so the cause is still
        unknown rather than diagnosed. The two updaters drifted because the rule lived twice.

    .PARAMETER Stage
        Where it failed, which is what decides the status:
          acquire -- Enter-BookLock did not return. Nothing has been touched, because the marker is
                     written INSIDE the lock, so `skipped` is accurate for every acquire failure --
                     contention, an empty Book root, or a lock directory that could not be created.
                     The message is passed through unchanged: Enter-BookLock's own contention text
                     already names the Book and the lock path.
          open    -- Enter-BookMutation threw. The marker may or may not be down, so the Book's
                     state on disk is unknown. `dirty` is still the outcome to report: it is the
                     status that counts toward dirty_books, exits non-zero, and tells the operator
                     to re-run -- the right action whether the slug is malformed or the marker
                     could not be written. The detail carries what actually happened.
          commit  -- generation or the transaction failed with the marker down. `dirty` and a
                     re-run, which is what Complete-BookMutation reports for itself.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$Slug,
        [Parameter(Mandatory = $true)][ValidateSet('acquire', 'open', 'commit')][string]$Stage,
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Message
    )

    # An empty message is how 'locked by another writer' outlived the truth for a year: a report
    # that carries no cause cannot be checked against what happened. Refuse it at the source.
    if ([string]::IsNullOrWhiteSpace($Message)) {
        throw "A '$Stage' failure must carry the message it failed with; a causeless report is the defect this function exists to prevent."
    }

    $status = if ($Stage -ceq 'acquire') { 'skipped' } else { 'dirty' }
    $summary = switch ($Stage) {
        'acquire' { $Message }
        'open'    { "the mutation window would not open: $Message" }
        'commit'  { "dirty until rebuilt: $Message" }
    }
    [pscustomobject]@{ status = $status; slug = $Slug; generation = 0; summary = $summary }
}

function Undo-BookMutation {
    <#
    .SYNOPSIS
        Close a mutation window whose mutation was rolled back and VERIFIED. Never throws.

    .DESCRIPTION
        Only for a rollback that verified, or for a failure that wrote nothing. The Book is then back
        to the state the committed manifest already describes, so the marker is stale and clearing it
        restores a true answer. After a rollback that FAILED the Book is in an unknown state and the
        marker must stay down -- do not call this there.
    #>
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)][object]$Mutation)

    try {
        $marker = Join-Path (Get-BookManifestStorePath -Workspace $Mutation.workspace -Slug $Mutation.slug -Collection $Mutation.collection) 'dirty.json'
        if (Test-Path -LiteralPath $marker -PathType Leaf) { Remove-Item -LiteralPath $marker -Force }
        [pscustomobject]@{ status = 'cleared'; slug = $Mutation.slug; generation = 0; summary = 'unchanged (the mutation was rolled back)' }
    }
    catch {
        [pscustomobject]@{ status = 'dirty'; slug = $Mutation.slug; generation = 0; summary = "dirty until rebuilt: the marker could not be cleared: $($_.Exception.Message)" }
    }
}

function Complete-BookRenameMutation {
    <#
    .SYNOPSIS
        Close a mutation window across a change of Book identity: the old slug's store is retired and
        the new slug's first generation is committed. Never throws.

    .DESCRIPTION
        A rename is the one mutation that changes which Book the manifest is about, and rung 2
        recorded the consequence as a known limit: the old slug's store survives as an orphan
        describing a Book at a path that no longer exists. It is not a leak -- the contents were
        always catalog-class -- but it is a stale answer waiting to be found.

        The manifest is not moved, it is retired and regenerated. Generation N of the old slug
        describes a Book with the old slug and the old title inside it; carrying those files forward
        under a new name would make the store's history disagree with itself. A manifest is derived
        state, so the cheap and truthful move is to throw it away and generate the new identity's
        first generation from the Book as it now stands.

        THE ORDER IS CHOSEN SO EVERY CRASH POINT REFUSES. The new identity is marked dirty first, the
        old store is removed second, and the new generation is committed last. A crash after the first
        step leaves an old store that is dirty and a new store that is dirty -- both refuse. A crash
        after the second leaves only the new store, dirty, refusing. At no point does a store answer
        for a Book that has moved.

        A CHANGE OF SHELF IS THE SAME MOVE. Archiving a Shelf Book changes its identity exactly as a
        rename does -- `shelf/<slug>` becomes `shelf/_archive/<slug>`, and its manifest must follow it
        into the `shelf-archive` store or the Book drops out of Discovery, which is what archiving
        used to do. So -NewCollection generalises this from "new slug" to "new identity", and the
        ordering argument above is unchanged: it never depended on WHICH field moved.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][object]$Mutation,
        [Parameter(Mandatory = $true)][string]$NewSlug,
        [string]$NewBookRoot = '',
        [Parameter(Mandatory = $true)][object]$NewLock,
        # Defaults to the mutation's own collection, which is what a rename wants.
        [string]$NewCollection = '',
        # Required whenever the new identity is not an active Shelf Book, for the reason
        # Invoke-BookManifestTransaction states: nothing here can read those pages.
        [object]$Manifest = $null
    )

    try {
        if ([string]::IsNullOrWhiteSpace($NewCollection)) { $NewCollection = $Mutation.collection }
        if ([string]::IsNullOrWhiteSpace($NewBookRoot)) { $NewBookRoot = New-BookRootFromManifestCollection $NewCollection $NewSlug }
        $renamed = Enter-BookMutation -Workspace $Mutation.workspace -Slug $NewSlug -BookRoot $NewBookRoot `
            -Reason $Mutation.reason -Lock $NewLock -Collection $NewCollection
        # -Collection, which this call did not pass before and did not need to while a rename was the
        # only caller: the parameter defaults to 'shelf', so a move out of any OTHER store would have
        # left the old manifest in place and deleted an unrelated Shelf Book's store if one shared the
        # slug. It is the mutation's own collection, never the new one.
        Remove-BookManifestStore -Workspace $Mutation.workspace -Slug $Mutation.slug -Collection $Mutation.collection | Out-Null
        $result = Complete-BookMutation -Mutation $renamed -Manifest $Manifest
        if ($result.status -ceq 'committed') {
            [pscustomobject]@{
                status     = 'committed'
                slug       = $NewSlug
                generation = $result.generation
                summary    = "generation $($result.generation) committed under $NewBookRoot; the store for $($Mutation.book_root) was retired"
            }
        }
        else { $result }
    }
    catch {
        [pscustomobject]@{
            status     = 'dirty'
            slug       = $NewSlug
            generation = 0
            summary    = "dirty until rebuilt: $($_.Exception.Message)"
        }
    }
}

# ---------------------------------------------------------------------------------------------------
# Self-test. Fixture-only and offline; run by Invoke-LibraryChecks.ps1 as
# `book-manifest-transaction.selftest`.
# ---------------------------------------------------------------------------------------------------
if ($MyInvocation.InvocationName -ne '.' -and $args -contains '-SelfTest') {
    $script:failures = [Collections.Generic.List[string]]::new()
    $script:checks = 0
    function Assert([bool]$Condition, [string]$Message) {
        $script:checks++
        if (-not $Condition) { [void]$script:failures.Add($Message) }
    }

    $utf8 = [Text.UTF8Encoding]::new($false)
    function Write-Fixture([string]$Path, [string]$Text) {
        $dir = Split-Path -Parent $Path
        if (-not (Test-Path -LiteralPath $dir -PathType Container)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        [IO.File]::WriteAllText($Path, $Text, $utf8)
    }

    $fixture = Join-Path ([IO.Path]::GetTempPath()) ('book-manifest-txn-selftest-' + [Guid]::NewGuid().ToString('n'))
    # An unexpected error inside the body would otherwise unwind straight past the remaining
    # assertions and be reported as a pass over however many had run -- observed on the first run of
    # this very suite, where a strict-mode property error left it announcing one check and success.
    try {
        Write-Fixture (Join-Path $fixture 'shelf/_catalog.md') @'
# Local Shelf

## Demo Book
- **Summary:** A curated demo Book for the manifest transaction.
- **Topics:** demo, curated
- **Path:** shelf/demo

## Inbox
- **Summary:** Captures awaiting review.
- **Topics:** capture
- **Kind:** capture
- **Path:** shelf/inbox
'@

        Write-Fixture (Join-Path $fixture 'shelf/demo/wiki/_book.md') "# Demo Book`n`n- **Type:** fixture`n"
        Write-Fixture (Join-Path $fixture 'shelf/demo/wiki/_index.md') "# Demo Book - Reader Map`n`n- [[_book|Book metadata]]`n- [[topic/plain]]`n"
        Write-Fixture (Join-Path $fixture 'shelf/demo/wiki/topic/plain.md') "# Real Title`n`nBody text.`n`n## A Real Section`n"

        Write-Fixture (Join-Path $fixture 'shelf/inbox/wiki/_book.md') "# Inbox`n`n- **Kind:** capture`n"
        Write-Fixture (Join-Path $fixture 'shelf/inbox/wiki/_index.md') "# Inbox - Reader Map`n`n- [[notes/secret-note|Sekrit Capture Title]]`n"
        Write-Fixture (Join-Path $fixture 'shelf/inbox/wiki/notes/secret-note.md') "---`ncaptured: 2026-08-18T00:00:00Z`nreview: pending`n---`n`n# Sekrit Capture Title`n`nUnvetted body.`n"

        $demoStore = Get-BookManifestStorePath -Workspace $fixture -Slug 'demo'
        $lockDir = Join-Path $fixture 'internal/book-locks'
        function Get-LockFiles {
            if (Test-Path -LiteralPath $lockDir -PathType Container) { @(Get-ChildItem -LiteralPath $lockDir -File -Filter '*.lock') } else { @() }
        }

        # --- A bad slug is refused before any lock exists --------------------------------------------
        $refused = $false
        try { Invoke-BookManifestTransaction -Workspace $fixture -Slug 'Foo' -Reason 'selftest bad slug' | Out-Null }
        catch { $refused = $true }
        Assert $refused 'an invalid slug was accepted by the transaction'
        Assert (@(Get-LockFiles).Count -eq 0) 'a refused slug left a lock file behind'

        # --- The lock is taken BEFORE the dirty marker -----------------------------------------------
        # Held by another writer, the transaction must fail having written nothing at all. Were the
        # marker set first, this Book would now read dirty with no mutation behind it to repair.
        $blocker = Enter-BookLock -Workspace $fixture -BookRoot 'shelf/demo' -TimeoutSeconds 5
        $blocked = $false
        try { Invoke-BookManifestTransaction -Workspace $fixture -Slug 'demo' -Reason 'selftest blocked' -TimeoutSeconds 1 | Out-Null }
        catch { $blocked = $true }
        Assert $blocked 'the transaction ran while another writer held the Book lock'
        Assert (-not (Test-Path -LiteralPath (Join-Path $demoStore 'dirty.json') -PathType Leaf)) 'a blocked transaction set a dirty marker'
        Assert ((Get-StoredBookManifest -Workspace $fixture -Slug 'demo').status -ceq 'missing') 'a blocked transaction left stored state behind'

        # --- A caller that already holds the lock passes it in ---------------------------------------
        $passed = Invoke-BookManifestTransaction -Workspace $fixture -Slug 'demo' -Reason 'selftest caller lock' -Lock $blocker
        Assert ($passed.generation -eq 1) "the first committed generation was $($passed.generation), not 1"
        Assert (-not $passed.lock_acquired) 'the transaction reported acquiring a lock it was handed'
        Assert (Test-Path -LiteralPath $blocker.path -PathType Leaf) 'the transaction released a lock it did not acquire'
        Assert ((Get-StoredBookManifest -Workspace $fixture -Slug 'demo').status -ceq 'ok') 'the manifest committed under a caller lock did not read back ok'
        Exit-BookLock -Lock $blocker

        # --- A lock for a different Book is refused, and nothing is written ---------------------------
        $wrong = Enter-BookLock -Workspace $fixture -BookRoot 'shelf/other' -TimeoutSeconds 5
        $mismatch = $false
        try { Invoke-BookManifestTransaction -Workspace $fixture -Slug 'demo' -Reason 'selftest wrong lock' -Lock $wrong | Out-Null }
        catch { $mismatch = $true }
        Assert $mismatch 'a lock for another Book was accepted as this Book''s lock'
        Assert (-not (Test-Path -LiteralPath (Join-Path $demoStore 'dirty.json') -PathType Leaf)) 'a mismatched lock still set a dirty marker'
        Exit-BookLock -Lock $wrong

        # --- The same Book spelled differently is the same lock ---------------------------------------
        $spelled = Enter-BookLock -Workspace $fixture -BookRoot 'shelf/demo/' -TimeoutSeconds 5
        $viaSpelling = Invoke-BookManifestTransaction -Workspace $fixture -Slug 'demo' -BookRoot 'shelf/demo' -Reason 'selftest lock spelling' -Lock $spelled
        Assert ($viaSpelling.generation -eq 2) 'a lock taken under an equivalent Book root spelling was not accepted'
        Exit-BookLock -Lock $spelled

        # --- Acquiring its own lock, and releasing it ------------------------------------------------
        $own = Invoke-BookManifestTransaction -Workspace $fixture -Slug 'demo' -Reason 'selftest own lock'
        Assert $own.lock_acquired 'the transaction did not report acquiring its own lock'
        Assert (@(Get-LockFiles).Count -eq 0) 'the transaction kept the lock it acquired'
        Assert ($own.generation -eq 3) "the third committed generation was $($own.generation)"

        # --- Determinism survives the transaction -----------------------------------------------------
        $again = Invoke-BookManifestTransaction -Workspace $fixture -Slug 'demo' -Reason 'selftest determinism'
        Assert ($again.manifest_sha256 -ceq $own.manifest_sha256) 'an unchanged Book produced a different manifest hash through the transaction'
        $generated = New-BookManifest -Workspace $fixture -Slug 'demo'
        $read = Get-StoredBookManifest -Workspace $fixture -Slug 'demo'
        Assert (($read.manifest | ConvertTo-Json -Depth 12) -ceq ($generated | ConvertTo-Json -Depth 12)) 'the committed manifest is not the one generation produces'
        Assert ($read.source_digest -ceq $generated.source_digest) 'the committed source_digest does not match the Book'

        # --- A failure AFTER the marker leaves the Book dirty, and still releases the lock -------------
        # Whatever called this has already mutated the Book, so a stale manifest served as fresh is
        # the one outcome worse than a refusal: the marker stays and the read path keeps refusing.
        $failed = $false
        try { Invoke-BookManifestTransaction -Workspace $fixture -Slug 'demo' -Reason 'selftest mid-failure' -Manifest ([pscustomobject]@{ schema = 1 }) | Out-Null }
        catch { $failed = $true }
        Assert $failed 'a malformed manifest was committed without error'
        Assert (Test-Path -LiteralPath (Join-Path $demoStore 'dirty.json') -PathType Leaf) 'a failed transaction cleared the dirty marker'
        Assert ((Get-StoredBookManifest -Workspace $fixture -Slug 'demo').status -ceq 'dirty') 'a failed transaction left the Book readable'
        Assert (@(Get-LockFiles).Count -eq 0) 'a failed transaction kept the lock'
        Remove-Item -LiteralPath (Join-Path $demoStore 'dirty.json') -Force

        # --- A failure BEFORE the marker leaves no marker at all ---------------------------------------
        # An uncatalogued Book is refused by generation. A marker written here would be a Book that
        # reads unavailable forever, with no mutation behind it that a rebuild could repair.
        $uncatalogued = $false
        try { Invoke-BookManifestTransaction -Workspace $fixture -Slug 'nowhere' -Reason 'selftest uncatalogued' | Out-Null }
        catch { $uncatalogued = $true }
        Assert $uncatalogued 'an uncatalogued Book was generated by the transaction'
        Assert (-not (Test-Path -LiteralPath (Join-Path (Get-BookManifestStorePath -Workspace $fixture -Slug 'nowhere') 'dirty.json') -PathType Leaf)) 'a generation failure left a dirty marker behind'
        Assert (@(Get-LockFiles).Count -eq 0) 'a generation failure kept the lock'

        # --- The leak canary, carried through the transaction -------------------------------------------
        $inbox = Invoke-BookManifestTransaction -Workspace $fixture -Slug 'inbox' -Reason 'selftest capture'
        $inboxGen = Join-Path (Get-BookManifestStorePath -Workspace $fixture -Slug 'inbox') "generations/$($inbox.generation).json"
        $inboxText = [IO.File]::ReadAllText($inboxGen)
        Assert ($inboxText -cnotmatch 'Sekrit Capture Title') 'a capture note title reached the committed generation file'
        Assert ($inboxText -cnotmatch 'secret-note') 'a capture note path reached the committed generation file'
        Assert ($inboxText -cnotmatch 'Unvetted body') 'capture note body text reached the committed generation file'

        # --- The mutation window: the marker is down BEFORE the writer touches anything --------------
        # This is the half rung 4 adds. A writer that only committed AFTERWARDS would leave the Book
        # reading `ok` for the whole span between its last write and its commit -- a stale manifest
        # that answers, which is the one outcome the marker exists to prevent.
        $mutLock = Enter-BookLock -Workspace $fixture -BookRoot 'shelf/demo' -TimeoutSeconds 5
        $mutation = Enter-BookMutation -Workspace $fixture -Slug 'demo' -Reason 'selftest window' -Lock $mutLock
        Assert ((Get-StoredBookManifest -Workspace $fixture -Slug 'demo').status -ceq 'dirty') 'an open mutation window still read as available'
        Write-Fixture (Join-Path $fixture 'shelf/demo/wiki/topic/added.md') "# Added Under The Window`n`n## A New Section`n"
        $closed = Complete-BookMutation -Mutation $mutation
        Assert ($closed.status -ceq 'committed') "closing the mutation window reported $($closed.status)"
        $afterWindow = Get-StoredBookManifest -Workspace $fixture -Slug 'demo'
        Assert ($afterWindow.status -ceq 'ok') 'a closed mutation window did not read back ok'
        Assert ($afterWindow.source_digest -ceq (New-BookManifest -Workspace $fixture -Slug 'demo').source_digest) 'the committed manifest does not describe the Book as it now stands'
        Assert (Test-Path -LiteralPath $mutLock.path -PathType Leaf) 'closing a mutation window released the writer''s lock'

        # --- A lock for another Book cannot open a window, and sets no marker ------------------------
        $foreign = Enter-BookLock -Workspace $fixture -BookRoot 'shelf/elsewhere' -TimeoutSeconds 5
        $windowRefused = $false
        try { Enter-BookMutation -Workspace $fixture -Slug 'demo' -Reason 'selftest foreign lock' -Lock $foreign | Out-Null }
        catch { $windowRefused = $true }
        Assert $windowRefused 'a window opened on another Book''s lock'
        Assert ((Get-StoredBookManifest -Workspace $fixture -Slug 'demo').status -ceq 'ok') 'a refused window still marked the Book dirty'
        Exit-BookLock -Lock $foreign

        # --- A verified rollback clears the marker; the previous manifest is true again --------------
        $priorGeneration = $afterWindow.generation
        $rolledBack = Enter-BookMutation -Workspace $fixture -Slug 'demo' -Reason 'selftest rollback' -Lock $mutLock
        Assert ((Get-StoredBookManifest -Workspace $fixture -Slug 'demo').status -ceq 'dirty') 'the rollback window did not mark the Book dirty'
        $undone = Undo-BookMutation -Mutation $rolledBack
        Assert ($undone.status -ceq 'cleared') "undoing a mutation reported $($undone.status)"
        $afterUndo = Get-StoredBookManifest -Workspace $fixture -Slug 'demo'
        Assert ($afterUndo.status -ceq 'ok') 'an undone mutation left the Book unavailable'
        Assert ($afterUndo.generation -eq $priorGeneration) 'an undone mutation moved the committed generation'

        # --- Completing NEVER throws, so a manifest failure cannot undo a landed write ---------------
        # An uncatalogued Book is refused by generation. The writer that got here has already changed
        # the Book, so the honest outcome is a reported refusal and a marker left standing -- never an
        # exception that unwinds into the writer's rollback and discards the reader's material.
        $orphanLock = Enter-BookLock -Workspace $fixture -BookRoot 'shelf/nowhere' -TimeoutSeconds 5
        $orphan = Enter-BookMutation -Workspace $fixture -Slug 'nowhere' -Reason 'selftest uncatalogued window' -Lock $orphanLock
        $orphanResult = Complete-BookMutation -Mutation $orphan
        Assert ($orphanResult.status -ceq 'dirty') 'a failed manifest generation was not reported as dirty'
        Assert ($orphanResult.summary -cmatch 'dirty until rebuilt') 'the dirty status did not say what it costs to repair'
        Assert ((Get-StoredBookManifest -Workspace $fixture -Slug 'nowhere').status -ceq 'dirty') 'a failed completion cleared the marker'
        Exit-BookLock -Lock $orphanLock
        Remove-BookManifestStore -Workspace $fixture -Slug 'nowhere' | Out-Null

        # --- A change of identity retires the old store rather than orphaning it ---------------------
        Write-Fixture (Join-Path $fixture 'shelf/_catalog.md') @'
# Local Shelf

## Demo Book Renamed
- **Summary:** A curated demo Book for the manifest transaction.
- **Topics:** demo, curated
- **Path:** shelf/renamed

## Inbox
- **Summary:** Captures awaiting review.
- **Topics:** capture
- **Kind:** capture
- **Path:** shelf/inbox
'@
        $renameMutation = Enter-BookMutation -Workspace $fixture -Slug 'demo' -Reason 'selftest rename' -Lock $mutLock
        Move-Item -LiteralPath (Join-Path $fixture 'shelf/demo') -Destination (Join-Path $fixture 'shelf/renamed')
        $renamedLock = Enter-BookLock -Workspace $fixture -BookRoot 'shelf/renamed' -TimeoutSeconds 5
        $renameResult = Complete-BookRenameMutation -Mutation $renameMutation -NewSlug 'renamed' -NewLock $renamedLock
        Assert ($renameResult.status -ceq 'committed') "the rename completion reported $($renameResult.status)"
        Assert (-not (Test-Path -LiteralPath $demoStore)) 'the renamed Book left its old store behind as an orphan'
        $afterRename = Get-StoredBookManifest -Workspace $fixture -Slug 'renamed'
        Assert ($afterRename.status -ceq 'ok') 'the renamed Book''s store did not read back ok'
        Assert ($afterRename.manifest.slug -ceq 'renamed') 'the committed manifest still names the old slug'
        Assert ($renameResult.generation -eq 1) "the renamed identity started at generation $($renameResult.generation), not 1"
        Exit-BookLock -Lock $renamedLock
        Exit-BookLock -Lock $mutLock
        Assert (@(Get-LockFiles).Count -eq 0) 'the mutation-window cases left a lock behind'
    }
    catch {
        [void]$script:failures.Add("the suite did not run to completion: $($_.Exception.Message)")
    }
    finally {
        Remove-Item -LiteralPath $fixture -Recurse -Force -ErrorAction SilentlyContinue
    }

    if ($script:failures.Count) {
        [Console]::Error.WriteLine("BookManifestTransaction self-test FAILED: $($script:failures -join '; ')")
        exit 1
    }
    Write-Host "BookManifestTransaction self-test passed ($($script:checks) checks)."
    exit 0
}
