<#
.SYNOPSIS
    The canonical plugin package, the Claude files generated from it, and the one table that names
    an installed MCP tool. Dot-sourced; never invoked directly except with -SelfTest or -Write.

.DESCRIPTION
    PLAN-public-release.md step 19. The Codex layout under `plugin/` is CANONICAL -- `plugin.json`,
    `mcp.json`, `hooks/hooks.json`, `skills/`. Claude's `.claude-plugin/plugin.json`, its `.mcp.json`
    and its hooks file are GENERATED from those by this module and never hand-maintained;
    `plugin.generated-files-match` regenerates them and fails the gate on any drift.

    WHY A TABLE AT ALL, WHEN docs/mcp-tool-allowlist-check.md SAYS NOT TO KEEP ONE. That decision --
    "the tool list is asked of the adapter, not kept beside it" -- still stands and is honoured here:
    nothing in this file names a single tool. What a plugin adds is a PREFIX the adapter cannot know,
    because it is composed by the harness at install time out of the plugin id and the server id.
    So the table is not a list of tools; it is the COMPOSITION RULE, and the tool names that go
    through it are still asked of the adapter over JSON-RPC. That distinction is the whole of step
    19's "one table" question.

    THE THREE FORMS, AND WHY THEY DIFFER.
      project   mcp__<server>__<tool>                     a server in a workspace .mcp.json
      plugin    mcp__plugin_<plugin>_<server>__<tool>     the same server supplied by a plugin
      codex     mcp__<server>__<tool>                     Codex does not re-scope a plugin's server

    Only the `project` form is verified against a live client here: this workspace declares the
    reader in `.mcp.json` today, so `Test-PluginToolNamesAgainstSession` can compare the composed
    names against names a real session actually offers. The `plugin` form is a COMPOSITION, not a
    measurement -- no session has yet started with this package installed -- and it is marked as
    such rather than reported as captured. See the spike report in
    PLAN-REVIEW-LOG-public-release.md.
#>
[CmdletBinding()]
param(
    [switch]$SelfTest,
    [switch]$Write,
    [string]$Workspace
)

Set-StrictMode -Version Latest

$script:GeneratedHeaderKey = '_generated'
$script:GeneratedNotice = 'GENERATED by tools/PluginPackage.ps1 from the canonical Codex-layout package under plugin/. Do not hand-edit: plugin.generated-files-match fails the gate on a drift.'

function Get-PluginWorkspace([string]$Candidate) {
    if ($Candidate) { return (Resolve-Path -LiteralPath $Candidate).Path }
    (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path
}

# --- reading the canonical package ----------------------------------------------------------------
function Read-PluginCanonical {
    param([Parameter(Mandatory)][string]$Workspace)
    $root = Join-Path $Workspace 'plugin'
    if (-not (Test-Path -LiteralPath $root -PathType Container)) {
        throw "there is no canonical plugin package at $root, so nothing can be generated from it."
    }
    $result = @{ root = $root }
    foreach ($pair in @(
            @{ key = 'manifest'; path = 'plugin.json' },
            @{ key = 'mcp';      path = 'mcp.json' },
            @{ key = 'hooks';    path = 'hooks/hooks.json' })) {
        $full = Join-Path $root $pair.path
        if (-not (Test-Path -LiteralPath $full -PathType Leaf)) {
            throw "the canonical plugin package has no $($pair.path); the Codex layout is the source and it is incomplete."
        }
        try { $result[$pair.key] = [IO.File]::ReadAllText($full, [Text.UTF8Encoding]::new($false)) | ConvertFrom-Json }
        catch { throw "plugin/$($pair.path) is not valid JSON: $($_.Exception.Message)" }
    }
    $result
}

function Get-PluginId {
    param([Parameter(Mandatory)]$Canonical)
    $name = [string]$Canonical.manifest.name
    if ([string]::IsNullOrWhiteSpace($name)) { throw 'plugin/plugin.json declares no name; an installed tool name cannot be composed without it.' }
    $name
}

function Get-PluginServerId {
    param([Parameter(Mandatory)]$Canonical)
    $names = @($Canonical.mcp.PSObject.Properties | ForEach-Object { $_.Name })
    if ($names -cnotcontains 'mcpServers') { throw 'plugin/mcp.json carries no mcpServers section.' }
    $servers = @($Canonical.mcp.mcpServers.PSObject.Properties | ForEach-Object { $_.Name })
    # EXACTLY ONE, asserted rather than assumed. Step 19's ruling is that the plugin exposes one MCP
    # server, the Library's own, with Basic Memory reached behind it -- a second server here would
    # make the composition below ambiguous AND would put a peer server in the reader's harness that
    # the guard was never designed to cover.
    if ($servers.Count -ne 1) {
        throw "plugin/mcp.json declares $($servers.Count) MCP server(s); the package must expose exactly one, the Library's own."
    }
    $servers[0]
}

# --- THE ONE TABLE --------------------------------------------------------------------------------
function Get-PluginToolNameForm {
    <#
        The composition rule, in one place. Every matcher, allowlist entry, guard comparison and
        advertised reader name is supposed to come through here rather than being typed.
    #>
    param(
        [Parameter(Mandatory)][ValidateSet('project', 'plugin', 'codex')][string]$Mode,
        [Parameter(Mandatory)][string]$PluginId,
        [Parameter(Mandatory)][string]$ServerId,
        [Parameter(Mandatory)][string]$Tool
    )
    switch ($Mode) {
        'project' { "mcp__${ServerId}__${Tool}" }
        'codex'   { "mcp__${ServerId}__${Tool}" }
        'plugin'  { "mcp__plugin_${PluginId}_${ServerId}__${Tool}" }
    }
}

function Get-PluginToolNames {
    <#
        Every installed name, in every mode, for every tool the ADAPTER declares. The tool names are
        asked, never listed here.
    #>
    param(
        [Parameter(Mandatory)][string]$Workspace,
        [string[]]$ToolNames
    )
    $canonical = Read-PluginCanonical -Workspace $Workspace
    $pluginId = Get-PluginId -Canonical $canonical
    $serverId = Get-PluginServerId -Canonical $canonical

    $tools = @($ToolNames | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    if (-not $tools.Count) { $tools = @(Get-PluginAdapterTools -Workspace $Workspace -ServerId $serverId) }
    if (-not $tools.Count) {
        throw 'the adapter declared no tools, so no installed name can be composed. A silent adapter read as "declares nothing" is the quiet clean answer this must never give.'
    }

    $rows = [Collections.Generic.List[object]]::new()
    foreach ($tool in ($tools | Sort-Object)) {
        [void]$rows.Add([pscustomobject]@{
            tool    = $tool
            project = Get-PluginToolNameForm -Mode 'project' -PluginId $pluginId -ServerId $serverId -Tool $tool
            plugin  = Get-PluginToolNameForm -Mode 'plugin'  -PluginId $pluginId -ServerId $serverId -Tool $tool
            codex   = Get-PluginToolNameForm -Mode 'codex'   -PluginId $pluginId -ServerId $serverId -Tool $tool
        })
    }
    @($rows)
}

function Get-PluginAdapterTools {
    <#
        Ask the workspace's own adapter what it declares, over the same JSON-RPC stdio channel the
        reader's client uses. Reuses tools/McpToolInventory.ps1 rather than opening a second way to
        ask the same question.
    #>
    param([Parameter(Mandatory)][string]$Workspace, [Parameter(Mandatory)][string]$ServerId)
    . (Join-Path $PSScriptRoot 'McpToolInventory.ps1')
    # The inventory's rows name the server in `server` and its arguments in `arguments`; reading
    # `name`/`args` here threw under StrictMode and the catch reported "declares no server", which
    # is a different fault entirely. Shape first, then values.
    $servers = @(Get-McpConfiguredServer -Workspace $Workspace)
    $match = @($servers | Where-Object { [string]$_.server -ceq $ServerId })
    if (-not $match.Count) {
        $seen = @($servers | ForEach-Object { [string]$_.server }) -join ', '
        throw "this workspace's .mcp.json declares no server named '$ServerId'; it declares: $seen."
    }
    if (-not $match[0].enumerable) {
        throw "the server '$ServerId' is not enumerable offline ($([string]$match[0].reason)), so its tool names cannot be asked for here."
    }
    @(Invoke-McpToolsList -Command $match[0].command -ArgumentList @($match[0].arguments) -WorkingDirectory $Workspace)
}

# --- generation -----------------------------------------------------------------------------------
function ConvertTo-PluginJsonText($Value) {
    # Pretty, stable, and newline-normalised, so a generated file is reviewable in a diff and a
    # regeneration on the same machine is byte-identical.
    $text = $Value | ConvertTo-Json -Depth 30
    ($text -replace "`r`n", "`n").TrimEnd() + "`n"
}

function ConvertTo-PluginCanonicalJson($Value) {
    <#
        A formatting-independent form, used ONLY for comparison. The gate must fail on a CHANGED
        MANIFEST, not on a PowerShell release that indents differently -- comparing rendered text
        would make the check report drift for an upgrade nobody performed.
    #>
    if ($null -eq $Value) { return 'null' }
    if ($Value -is [string]) { return (ConvertTo-Json $Value -Compress) }
    if ($Value -is [bool] -or $Value -is [int] -or $Value -is [long] -or $Value -is [double] -or $Value -is [decimal]) {
        return (ConvertTo-Json $Value -Compress)
    }
    if ($Value -is [Array]) {
        return '[' + ((@($Value) | ForEach-Object { ConvertTo-PluginCanonicalJson $_ }) -join ',') + ']'
    }
    $names = @($Value.PSObject.Properties | ForEach-Object { $_.Name } | Sort-Object)
    $parts = foreach ($name in $names) {
        (ConvertTo-Json $name -Compress) + ':' + (ConvertTo-PluginCanonicalJson $Value.$name)
    }
    '{' + (@($parts) -join ',') + '}'
}

function ConvertTo-ClaudeHookRoot($Value) {
    # THE ONE MECHANICAL DIFFERENCE between the two harnesses' hook files. Codex expands
    # ${PLUGIN_ROOT}; Claude expands ${CLAUDE_PLUGIN_ROOT}. Everything else is carried through
    # verbatim, so a matcher or a timeout can only be changed in the canonical file.
    if ($Value -is [string]) { return ($Value -replace '\$\{PLUGIN_ROOT\}', '${CLAUDE_PLUGIN_ROOT}') }
    if ($Value -is [Array]) { return @(@($Value) | ForEach-Object { ConvertTo-ClaudeHookRoot $_ }) }
    if ($null -eq $Value -or $Value -is [bool] -or $Value -is [int] -or $Value -is [long] -or $Value -is [double]) { return $Value }
    $ordered = [ordered]@{}
    foreach ($property in @($Value.PSObject.Properties)) { $ordered[$property.Name] = ConvertTo-ClaudeHookRoot $property.Value }
    [pscustomobject]$ordered
}

function New-ClaudeGeneratedFiles {
    <#
        Returns the generated Claude files as published-path -> object, ready to be written or
        compared. Nothing here is written to disk.
    #>
    param([Parameter(Mandatory)][string]$Workspace)
    $canonical = Read-PluginCanonical -Workspace $Workspace
    $manifest = $canonical.manifest

    $pluginManifest = [ordered]@{
        $script:GeneratedHeaderKey = $script:GeneratedNotice
        name        = [string]$manifest.name
        description = [string]$manifest.description
        version     = [string]$manifest.version
        author      = $manifest.author
        repository  = [string]$manifest.repository
    }

    # Claude's plugin MCP config takes the same mcpServers object, with the root variable rewritten.
    $mcpConfig = [ordered]@{
        $script:GeneratedHeaderKey = $script:GeneratedNotice
        mcpServers = (ConvertTo-ClaudeHookRoot $canonical.mcp.mcpServers)
    }

    $hooksConfig = [ordered]@{
        description = $script:GeneratedNotice + ' Source: plugin/hooks/hooks.json. ' + [string]$canonical.hooks.description
        hooks       = (ConvertTo-ClaudeHookRoot $canonical.hooks.hooks)
    }

    [ordered]@{
        '.claude-plugin/plugin.json'      = [pscustomobject]$pluginManifest
        '.claude-plugin/.mcp.json'        = [pscustomobject]$mcpConfig
        '.claude-plugin/hooks/hooks.json' = [pscustomobject]$hooksConfig
    }
}

function Write-PluginGeneratedFiles {
    param([Parameter(Mandatory)][string]$Workspace)
    $root = Join-Path $Workspace 'plugin'
    $generated = New-ClaudeGeneratedFiles -Workspace $Workspace
    $written = [Collections.Generic.List[string]]::new()
    foreach ($relative in @($generated.Keys)) {
        $target = Join-Path $root $relative
        $parent = Split-Path -Parent $target
        if (-not (Test-Path -LiteralPath $parent -PathType Container)) { [void](New-Item -ItemType Directory -Path $parent -Force) }
        [IO.File]::WriteAllText($target, (ConvertTo-PluginJsonText $generated[$relative]), [Text.UTF8Encoding]::new($false))
        [void]$written.Add($relative)
    }
    @($written)
}

function Test-PluginGeneratedFiles {
    <#
        Regenerate in memory and compare against what is committed. Returns one fault per file that
        is missing, unparseable or different.
    #>
    param([Parameter(Mandatory)][string]$Workspace)
    $root = Join-Path $Workspace 'plugin'
    $generated = New-ClaudeGeneratedFiles -Workspace $Workspace
    $faults = [Collections.Generic.List[string]]::new()
    # EXAMINED, not "agreed". A drifted file HAS been read and compared -- counting it as unexamined
    # made the coverage assertion below fire alongside the real fault and report that this check had
    # not read what it claims, which was false and buried the one message that mattered.
    $examined = 0
    $unreadable = 0
    foreach ($relative in @($generated.Keys)) {
        $target = Join-Path $root $relative
        if (-not (Test-Path -LiteralPath $target -PathType Leaf)) {
            [void]$faults.Add("plugin/$relative is missing; regenerate with tools/PluginPackage.ps1 -Write")
            $unreadable++
            continue
        }
        try { $onDisk = [IO.File]::ReadAllText($target, [Text.UTF8Encoding]::new($false)) | ConvertFrom-Json }
        catch {
            [void]$faults.Add("plugin/$relative is not valid JSON: $($_.Exception.Message)")
            $unreadable++
            continue
        }
        $expected = ConvertTo-PluginCanonicalJson $generated[$relative]
        $actual = ConvertTo-PluginCanonicalJson $onDisk
        if ($expected -cne $actual) {
            [void]$faults.Add("plugin/$relative does not match what the canonical package generates; it was hand-edited or the canonical file moved on")
        }
        $examined++
    }
    # ASSERTED FROM OUTSIDE THE LOOP: a generated file dropped from the set above would leave the
    # numerator and the denominator agreeing and the check reading clean.
    if ($examined + $unreadable -ne @($generated.Keys).Count) {
        [void]$faults.Add('the generated-file set and the examined count disagree; this check did not read what it claims to have read')
    }
    [pscustomobject]@{ faults = @($faults); compared = $examined; total = @($generated.Keys).Count }
}

# --- self-test ------------------------------------------------------------------------------------
function Invoke-PluginPackageSelfTest {
    param([Parameter(Mandatory)][string]$Workspace)
    $failures = 0
    function Check([bool]$Condition, [string]$Message) {
        if ($Condition) { Write-Output "  ok   $Message" } else { Write-Output "  FAIL $Message"; $script:SelfTestFailures++ }
    }
    $script:SelfTestFailures = 0

    $canonical = Read-PluginCanonical -Workspace $Workspace
    $pluginId = Get-PluginId -Canonical $canonical
    $serverId = Get-PluginServerId -Canonical $canonical
    Check ($pluginId -ceq 'deskpost') "the canonical package names the plugin 'deskpost' (got '$pluginId')"
    Check (-not [string]::IsNullOrWhiteSpace($serverId)) "the canonical package declares exactly one MCP server ('$serverId')"

    # The composition rule, against a tool name the fixture supplies rather than one asked of a live
    # adapter: this case is about the RULE, and an adapter round-trip here would make it a test of
    # the adapter instead.
    $rows = @(Get-PluginToolNames -Workspace $Workspace -ToolNames @('read_open_book_page'))
    Check ($rows.Count -eq 1) "one tool in, one row out (got $($rows.Count))"
    Check ($rows[0].project -ceq "mcp__${serverId}__read_open_book_page") "project form: $($rows[0].project)"
    Check ($rows[0].plugin -ceq "mcp__plugin_${pluginId}_${serverId}__read_open_book_page") "plugin form: $($rows[0].plugin)"
    Check ($rows[0].codex -ceq "mcp__${serverId}__read_open_book_page") "codex form: $($rows[0].codex)"
    Check ($rows[0].plugin -cne $rows[0].project) 'the plugin form differs from the project form, which is the whole reason the table exists'

    # The root rewrite, in both directions.
    $rewritten = ConvertTo-ClaudeHookRoot ([pscustomobject]@{ command = 'x "${PLUGIN_ROOT}/hooks/A.ps1" y' })
    Check ($rewritten.command -ceq 'x "${CLAUDE_PLUGIN_ROOT}/hooks/A.ps1" y') 'the Claude form rewrites ${PLUGIN_ROOT} to ${CLAUDE_PLUGIN_ROOT}'
    $untouched = ConvertTo-ClaudeHookRoot ([pscustomobject]@{ matcher = '^(Bash|exec)$'; timeout = 30 })
    Check ($untouched.matcher -ceq '^(Bash|exec)$') 'a matcher is carried through verbatim'
    Check ($untouched.timeout -eq 30) 'a timeout is carried through verbatim'

    # Canonical JSON ignores key order and indentation but not values -- the property the drift
    # comparison depends on.
    $a = '{"b":1,"a":{"d":2,"c":[1,2]}}' | ConvertFrom-Json
    $b = '{"a":{"c":[1,2],"d":2},"b":1}' | ConvertFrom-Json
    $c = '{"a":{"c":[1,3],"d":2},"b":1}' | ConvertFrom-Json
    Check ((ConvertTo-PluginCanonicalJson $a) -ceq (ConvertTo-PluginCanonicalJson $b)) 'reordered keys compare equal'
    Check ((ConvertTo-PluginCanonicalJson $a) -cne (ConvertTo-PluginCanonicalJson $c)) 'a changed VALUE compares unequal'

    $state = Test-PluginGeneratedFiles -Workspace $Workspace
    Check ($state.faults.Count -eq 0) "the committed generated files match the canonical package ($($state.compared) of $($state.total) compared)$(if ($state.faults.Count) { ': ' + ($state.faults -join '; ') })"

    if ($script:SelfTestFailures) { throw "$($script:SelfTestFailures) plugin package self-test failure(s)" }
    Write-Output "passed: plugin package, $($state.compared) generated file(s) match the canonical Codex layout"
}

if ($SelfTest -or $Write) {
    try {
        $ws = Get-PluginWorkspace $Workspace
        if ($Write) {
            $written = @(Write-PluginGeneratedFiles -Workspace $ws)
            Write-Output "wrote $($written.Count) generated file(s): $($written -join ', ')"
        }
        if ($SelfTest) { Invoke-PluginPackageSelfTest -Workspace $ws }
        exit 0
    }
    catch {
        Write-Output "FAILED: $($_.Exception.Message)"
        exit 1
    }
}
